// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HttpGetMissionsResp } from "../models/index";
import {
  HttpGetMissionsRespFromJSON,
  HttpGetMissionsRespToJSON,
} from "../models/index";

/**
 *
 */
export class MissionsApi extends runtime.BaseAPI {
  /**
   * get missions
   */
  async missionsGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HttpGetMissionsResp>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/missions`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HttpGetMissionsRespFromJSON(jsonValue),
    );
  }

  /**
   * get missions
   */
  async missionsGet(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HttpGetMissionsResp> {
    const response = await this.missionsGetRaw(initOverrides);
    return await response.value();
  }
}
