// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { HttpUpdateTokensResp } from "../models/index";
import {
  HttpUpdateTokensRespFromJSON,
  HttpUpdateTokensRespToJSON,
} from "../models/index";

/**
 *
 */
export class StatesApi extends runtime.BaseAPI {
  /**
   * submit tokens
   */
  async statesTokensPutRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HttpUpdateTokensResp>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/states/tokens`,
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HttpUpdateTokensRespFromJSON(jsonValue),
    );
  }

  /**
   * submit tokens
   */
  async statesTokensPut(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HttpUpdateTokensResp> {
    const response = await this.statesTokensPutRaw(initOverrides);
    return await response.value();
  }
}
