// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsUserMission } from "./ModelsUserMission";
import {
  ModelsUserMissionFromJSON,
  ModelsUserMissionFromJSONTyped,
  ModelsUserMissionToJSON,
} from "./ModelsUserMission";

/**
 *
 * @export
 * @interface HttpCreateUserMissionResp
 */
export interface HttpCreateUserMissionResp {
  /**
   *
   * @type {ModelsUserMission}
   * @memberof HttpCreateUserMissionResp
   */
  userMission?: ModelsUserMission;
}

/**
 * Check if a given object implements the HttpCreateUserMissionResp interface.
 */
export function instanceOfHttpCreateUserMissionResp(
  value: object,
): value is HttpCreateUserMissionResp {
  return true;
}

export function HttpCreateUserMissionRespFromJSON(
  json: any,
): HttpCreateUserMissionResp {
  return HttpCreateUserMissionRespFromJSONTyped(json, false);
}

export function HttpCreateUserMissionRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpCreateUserMissionResp {
  if (json == null) {
    return json;
  }
  return {
    userMission:
      json["user_mission"] == null
        ? undefined
        : ModelsUserMissionFromJSON(json["user_mission"]),
  };
}

export function HttpCreateUserMissionRespToJSON(
  value?: HttpCreateUserMissionResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    user_mission: ModelsUserMissionToJSON(value["userMission"]),
  };
}
