// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsStateHPRegen } from "./ModelsStateHPRegen";
import {
  ModelsStateHPRegenFromJSON,
  ModelsStateHPRegenFromJSONTyped,
  ModelsStateHPRegenToJSON,
} from "./ModelsStateHPRegen";
import type { ModelsStatePepe } from "./ModelsStatePepe";
import {
  ModelsStatePepeFromJSON,
  ModelsStatePepeFromJSONTyped,
  ModelsStatePepeToJSON,
} from "./ModelsStatePepe";
import type { ModelsStateHP } from "./ModelsStateHP";
import {
  ModelsStateHPFromJSON,
  ModelsStateHPFromJSONTyped,
  ModelsStateHPToJSON,
} from "./ModelsStateHP";
import type { ModelsStateDoge } from "./ModelsStateDoge";
import {
  ModelsStateDogeFromJSON,
  ModelsStateDogeFromJSONTyped,
  ModelsStateDogeToJSON,
} from "./ModelsStateDoge";

/**
 *
 * @export
 * @interface HttpGetStateLevelsResp
 */
export interface HttpGetStateLevelsResp {
  /**
   *
   * @type {{ [key: string]: ModelsStateDoge; }}
   * @memberof HttpGetStateLevelsResp
   */
  stateDogeLevels?: { [key: string]: ModelsStateDoge };
  /**
   *
   * @type {{ [key: string]: ModelsStateHP; }}
   * @memberof HttpGetStateLevelsResp
   */
  stateHpLevels?: { [key: string]: ModelsStateHP };
  /**
   *
   * @type {{ [key: string]: ModelsStateHPRegen; }}
   * @memberof HttpGetStateLevelsResp
   */
  stateHpRegenLevels?: { [key: string]: ModelsStateHPRegen };
  /**
   *
   * @type {{ [key: string]: ModelsStatePepe; }}
   * @memberof HttpGetStateLevelsResp
   */
  statePepeLevels?: { [key: string]: ModelsStatePepe };
}

/**
 * Check if a given object implements the HttpGetStateLevelsResp interface.
 */
export function instanceOfHttpGetStateLevelsResp(
  value: object,
): value is HttpGetStateLevelsResp {
  return true;
}

export function HttpGetStateLevelsRespFromJSON(
  json: any,
): HttpGetStateLevelsResp {
  return HttpGetStateLevelsRespFromJSONTyped(json, false);
}

export function HttpGetStateLevelsRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpGetStateLevelsResp {
  if (json == null) {
    return json;
  }
  return {
    stateDogeLevels:
      json["state_doge_levels"] == null
        ? undefined
        : mapValues(json["state_doge_levels"], ModelsStateDogeFromJSON),
    stateHpLevels:
      json["state_hp_levels"] == null
        ? undefined
        : mapValues(json["state_hp_levels"], ModelsStateHPFromJSON),
    stateHpRegenLevels:
      json["state_hp_regen_levels"] == null
        ? undefined
        : mapValues(json["state_hp_regen_levels"], ModelsStateHPRegenFromJSON),
    statePepeLevels:
      json["state_pepe_levels"] == null
        ? undefined
        : mapValues(json["state_pepe_levels"], ModelsStatePepeFromJSON),
  };
}

export function HttpGetStateLevelsRespToJSON(
  value?: HttpGetStateLevelsResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    state_doge_levels:
      value["stateDogeLevels"] == null
        ? undefined
        : mapValues(value["stateDogeLevels"], ModelsStateDogeToJSON),
    state_hp_levels:
      value["stateHpLevels"] == null
        ? undefined
        : mapValues(value["stateHpLevels"], ModelsStateHPToJSON),
    state_hp_regen_levels:
      value["stateHpRegenLevels"] == null
        ? undefined
        : mapValues(value["stateHpRegenLevels"], ModelsStateHPRegenToJSON),
    state_pepe_levels:
      value["statePepeLevels"] == null
        ? undefined
        : mapValues(value["statePepeLevels"], ModelsStatePepeToJSON),
  };
}
