// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsState } from "./ModelsState";
import {
  ModelsStateFromJSON,
  ModelsStateFromJSONTyped,
  ModelsStateToJSON,
} from "./ModelsState";

/**
 *
 * @export
 * @interface HttpUpdateTokensResp
 */
export interface HttpUpdateTokensResp {
  /**
   *
   * @type {ModelsState}
   * @memberof HttpUpdateTokensResp
   */
  state?: ModelsState;
}

/**
 * Check if a given object implements the HttpUpdateTokensResp interface.
 */
export function instanceOfHttpUpdateTokensResp(
  value: object,
): value is HttpUpdateTokensResp {
  return true;
}

export function HttpUpdateTokensRespFromJSON(json: any): HttpUpdateTokensResp {
  return HttpUpdateTokensRespFromJSONTyped(json, false);
}

export function HttpUpdateTokensRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpUpdateTokensResp {
  if (json == null) {
    return json;
  }
  return {
    state:
      json["state"] == null ? undefined : ModelsStateFromJSON(json["state"]),
  };
}

export function HttpUpdateTokensRespToJSON(
  value?: HttpUpdateTokensResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    state: ModelsStateToJSON(value["state"]),
  };
}
