// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsState } from "./ModelsState";
import {
  ModelsStateFromJSON,
  ModelsStateFromJSONTyped,
  ModelsStateToJSON,
} from "./ModelsState";

/**
 *
 * @export
 * @interface HttpUpdateStateLevelResp
 */
export interface HttpUpdateStateLevelResp {
  /**
   *
   * @type {ModelsState}
   * @memberof HttpUpdateStateLevelResp
   */
  state?: ModelsState;
}

/**
 * Check if a given object implements the HttpUpdateStateLevelResp interface.
 */
export function instanceOfHttpUpdateStateLevelResp(
  value: object,
): value is HttpUpdateStateLevelResp {
  return true;
}

export function HttpUpdateStateLevelRespFromJSON(
  json: any,
): HttpUpdateStateLevelResp {
  return HttpUpdateStateLevelRespFromJSONTyped(json, false);
}

export function HttpUpdateStateLevelRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpUpdateStateLevelResp {
  if (json == null) {
    return json;
  }
  return {
    state:
      json["state"] == null ? undefined : ModelsStateFromJSON(json["state"]),
  };
}

export function HttpUpdateStateLevelRespToJSON(
  value?: HttpUpdateStateLevelResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    state: ModelsStateToJSON(value["state"]),
  };
}
