// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsMission } from "./ModelsMission";
import {
  ModelsMissionFromJSON,
  ModelsMissionFromJSONTyped,
  ModelsMissionToJSON,
} from "./ModelsMission";

/**
 *
 * @export
 * @interface HttpGetMissionsResp
 */
export interface HttpGetMissionsResp {
  /**
   *
   * @type {Array<ModelsMission>}
   * @memberof HttpGetMissionsResp
   */
  missions?: Array<ModelsMission>;
}

/**
 * Check if a given object implements the HttpGetMissionsResp interface.
 */
export function instanceOfHttpGetMissionsResp(
  value: object,
): value is HttpGetMissionsResp {
  return true;
}

export function HttpGetMissionsRespFromJSON(json: any): HttpGetMissionsResp {
  return HttpGetMissionsRespFromJSONTyped(json, false);
}

export function HttpGetMissionsRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpGetMissionsResp {
  if (json == null) {
    return json;
  }
  return {
    missions:
      json["missions"] == null
        ? undefined
        : (json["missions"] as Array<any>).map(ModelsMissionFromJSON),
  };
}

export function HttpGetMissionsRespToJSON(
  value?: HttpGetMissionsResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    missions:
      value["missions"] == null
        ? undefined
        : (value["missions"] as Array<any>).map(ModelsMissionToJSON),
  };
}
