// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsUserMission } from "./ModelsUserMission";
import {
  ModelsUserMissionFromJSON,
  ModelsUserMissionFromJSONTyped,
  ModelsUserMissionToJSON,
} from "./ModelsUserMission";

/**
 *
 * @export
 * @interface HttpGetUserMissionsResp
 */
export interface HttpGetUserMissionsResp {
  /**
   *
   * @type {Array<ModelsUserMission>}
   * @memberof HttpGetUserMissionsResp
   */
  userMissions?: Array<ModelsUserMission>;
}

/**
 * Check if a given object implements the HttpGetUserMissionsResp interface.
 */
export function instanceOfHttpGetUserMissionsResp(
  value: object,
): value is HttpGetUserMissionsResp {
  return true;
}

export function HttpGetUserMissionsRespFromJSON(
  json: any,
): HttpGetUserMissionsResp {
  return HttpGetUserMissionsRespFromJSONTyped(json, false);
}

export function HttpGetUserMissionsRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): HttpGetUserMissionsResp {
  if (json == null) {
    return json;
  }
  return {
    userMissions:
      json["user_missions"] == null
        ? undefined
        : (json["user_missions"] as Array<any>).map(ModelsUserMissionFromJSON),
  };
}

export function HttpGetUserMissionsRespToJSON(
  value?: HttpGetUserMissionsResp | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    user_missions:
      value["userMissions"] == null
        ? undefined
        : (value["userMissions"] as Array<any>).map(ModelsUserMissionToJSON),
  };
}
