// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsUser } from "./ModelsUser";
import {
  ModelsUserFromJSON,
  ModelsUserFromJSONTyped,
  ModelsUserToJSON,
} from "./ModelsUser";
import type { ModelsState } from "./ModelsState";
import {
  ModelsStateFromJSON,
  ModelsStateFromJSONTyped,
  ModelsStateToJSON,
} from "./ModelsState";

/**
 *
 * @export
 * @interface ModelsUserState
 */
export interface ModelsUserState {
  /**
   *
   * @type {ModelsState}
   * @memberof ModelsUserState
   */
  state?: ModelsState;
  /**
   *
   * @type {ModelsUser}
   * @memberof ModelsUserState
   */
  user?: ModelsUser;
}

/**
 * Check if a given object implements the ModelsUserState interface.
 */
export function instanceOfModelsUserState(
  value: object,
): value is ModelsUserState {
  return true;
}

export function ModelsUserStateFromJSON(json: any): ModelsUserState {
  return ModelsUserStateFromJSONTyped(json, false);
}

export function ModelsUserStateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsUserState {
  if (json == null) {
    return json;
  }
  return {
    state:
      json["state"] == null ? undefined : ModelsStateFromJSON(json["state"]),
    user: json["user"] == null ? undefined : ModelsUserFromJSON(json["user"]),
  };
}

export function ModelsUserStateToJSON(value?: ModelsUserState | null): any {
  if (value == null) {
    return value;
  }
  return {
    state: ModelsStateToJSON(value["state"]),
    user: ModelsUserToJSON(value["user"]),
  };
}
