// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TimeDuration } from "./TimeDuration";
import {
  TimeDurationFromJSON,
  TimeDurationFromJSONTyped,
  TimeDurationToJSON,
} from "./TimeDuration";

/**
 *
 * @export
 * @interface ModelsStateHPRegen
 */
export interface ModelsStateHPRegen {
  /**
   *
   * @type {TimeDuration}
   * @memberof ModelsStateHPRegen
   */
  delay?: TimeDuration;
  /**
   *
   * @type {number}
   * @memberof ModelsStateHPRegen
   */
  price?: number;
}

/**
 * Check if a given object implements the ModelsStateHPRegen interface.
 */
export function instanceOfModelsStateHPRegen(
  value: object,
): value is ModelsStateHPRegen {
  return true;
}

export function ModelsStateHPRegenFromJSON(json: any): ModelsStateHPRegen {
  return ModelsStateHPRegenFromJSONTyped(json, false);
}

export function ModelsStateHPRegenFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsStateHPRegen {
  if (json == null) {
    return json;
  }
  return {
    delay:
      json["delay"] == null ? undefined : TimeDurationFromJSON(json["delay"]),
    price: json["price"] == null ? undefined : json["price"],
  };
}

export function ModelsStateHPRegenToJSON(
  value?: ModelsStateHPRegen | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    delay: TimeDurationToJSON(value["delay"]),
    price: value["price"],
  };
}
