// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { GormDeletedAt } from "./GormDeletedAt";
import {
  GormDeletedAtFromJSON,
  GormDeletedAtFromJSONTyped,
  GormDeletedAtToJSON,
} from "./GormDeletedAt";
import type { ModelsMissionName } from "./ModelsMissionName";
import {
  ModelsMissionNameFromJSON,
  ModelsMissionNameFromJSONTyped,
  ModelsMissionNameToJSON,
} from "./ModelsMissionName";

/**
 *
 * @export
 * @interface ModelsMission
 */
export interface ModelsMission {
  /**
   *
   * @type {string}
   * @memberof ModelsMission
   */
  createdAt?: string;
  /**
   *
   * @type {GormDeletedAt}
   * @memberof ModelsMission
   */
  deletedAt?: GormDeletedAt;
  /**
   *
   * @type {number}
   * @memberof ModelsMission
   */
  id?: number;
  /**
   *
   * @type {ModelsMissionName}
   * @memberof ModelsMission
   */
  name?: ModelsMissionName;
  /**
   *
   * @type {number}
   * @memberof ModelsMission
   */
  reward?: number;
  /**
   *
   * @type {string}
   * @memberof ModelsMission
   */
  updatedAt?: string;
}

/**
 * Check if a given object implements the ModelsMission interface.
 */
export function instanceOfModelsMission(value: object): value is ModelsMission {
  return true;
}

export function ModelsMissionFromJSON(json: any): ModelsMission {
  return ModelsMissionFromJSONTyped(json, false);
}

export function ModelsMissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsMission {
  if (json == null) {
    return json;
  }
  return {
    createdAt: json["createdAt"] == null ? undefined : json["createdAt"],
    deletedAt:
      json["deletedAt"] == null
        ? undefined
        : GormDeletedAtFromJSON(json["deletedAt"]),
    id: json["id"] == null ? undefined : json["id"],
    name:
      json["name"] == null
        ? undefined
        : ModelsMissionNameFromJSON(json["name"]),
    reward: json["reward"] == null ? undefined : json["reward"],
    updatedAt: json["updatedAt"] == null ? undefined : json["updatedAt"],
  };
}

export function ModelsMissionToJSON(value?: ModelsMission | null): any {
  if (value == null) {
    return value;
  }
  return {
    createdAt: value["createdAt"],
    deletedAt: GormDeletedAtToJSON(value["deletedAt"]),
    id: value["id"],
    name: ModelsMissionNameToJSON(value["name"]),
    reward: value["reward"],
    updatedAt: value["updatedAt"],
  };
}
