// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TimeDuration } from "./TimeDuration";
import {
  TimeDurationFromJSON,
  TimeDurationFromJSONTyped,
  TimeDurationToJSON,
} from "./TimeDuration";

/**
 *
 * @export
 * @interface ModelsStatePepe
 */
export interface ModelsStatePepe {
  /**
   *
   * @type {TimeDuration}
   * @memberof ModelsStatePepe
   */
  duration?: TimeDuration;
  /**
   *
   * @type {number}
   * @memberof ModelsStatePepe
   */
  price?: number;
}

/**
 * Check if a given object implements the ModelsStatePepe interface.
 */
export function instanceOfModelsStatePepe(
  value: object,
): value is ModelsStatePepe {
  return true;
}

export function ModelsStatePepeFromJSON(json: any): ModelsStatePepe {
  return ModelsStatePepeFromJSONTyped(json, false);
}

export function ModelsStatePepeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsStatePepe {
  if (json == null) {
    return json;
  }
  return {
    duration:
      json["duration"] == null
        ? undefined
        : TimeDurationFromJSON(json["duration"]),
    price: json["price"] == null ? undefined : json["price"],
  };
}

export function ModelsStatePepeToJSON(value?: ModelsStatePepe | null): any {
  if (value == null) {
    return value;
  }
  return {
    duration: TimeDurationToJSON(value["duration"]),
    price: value["price"],
  };
}
