// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TimeDuration } from "./TimeDuration";
import {
  TimeDurationFromJSON,
  TimeDurationFromJSONTyped,
  TimeDurationToJSON,
} from "./TimeDuration";

/**
 *
 * @export
 * @interface ModelsStateDoge
 */
export interface ModelsStateDoge {
  /**
   *
   * @type {TimeDuration}
   * @memberof ModelsStateDoge
   */
  duration?: TimeDuration;
  /**
   *
   * @type {number}
   * @memberof ModelsStateDoge
   */
  price?: number;
}

/**
 * Check if a given object implements the ModelsStateDoge interface.
 */
export function instanceOfModelsStateDoge(
  value: object,
): value is ModelsStateDoge {
  return true;
}

export function ModelsStateDogeFromJSON(json: any): ModelsStateDoge {
  return ModelsStateDogeFromJSONTyped(json, false);
}

export function ModelsStateDogeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ModelsStateDoge {
  if (json == null) {
    return json;
  }
  return {
    duration:
      json["duration"] == null
        ? undefined
        : TimeDurationFromJSON(json["duration"]),
    price: json["price"] == null ? undefined : json["price"],
  };
}

export function ModelsStateDogeToJSON(value?: ModelsStateDoge | null): any {
  if (value == null) {
    return value;
  }
  return {
    duration: TimeDurationToJSON(value["duration"]),
    price: value["price"],
  };
}
