// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Meme Game
 * Meme Game API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const TimeDuration = {
  Nanosecond: 1,
  Microsecond: 1000,
  Millisecond: 1000000,
  Second: 1000000000,
  Minute: 60000000000,
  Hour: 3600000000000,
} as const;
export type TimeDuration = (typeof TimeDuration)[keyof typeof TimeDuration];

export function instanceOfTimeDuration(value: any): boolean {
  for (const key in TimeDuration) {
    if (Object.prototype.hasOwnProperty.call(TimeDuration, key)) {
      if (TimeDuration[key] === value) {
        return true;
      }
    }
  }
  return false;
}

export function TimeDurationFromJSON(json: any): TimeDuration {
  return TimeDurationFromJSONTyped(json, false);
}

export function TimeDurationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TimeDuration {
  return json as TimeDuration;
}

export function TimeDurationToJSON(value?: TimeDuration | null): any {
  return value as any;
}
